In [2]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
df.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [8]:
df['deck']

df["deck"].isnull().sum()
len(df)

891

In [14]:
df["age"].mean()
df_clean = df.copy()
df_clean["age"] = df_clean["age"].fillna(df_clean["age"].mean())
df_clean["age"].isnull().sum()
df_clean["age"].mean()

np.float64(29.69911764705882)

In [35]:
#df_clean = df_clean.drop(columns=["alive"])
#df_clean = df_clean.drop(columns=["embarked_town"])
df_clean.head()
#df_clean = df_clean.drop(columns=["adult_male"])
#df_clean = df_clean.drop(columns=["embark_town"])
#df_clean = df_clean.drop(columns=["class"])
#df_clean = df_clean.drop(columns=["who"])
df_clean = df_clean.drop(columns=["deck"])

In [43]:
#df_clean["sex"] = df_clean["who"]
#df_clean["sex"] = df_clean["sex"].fillna("female").map({"man": 0, "woman": 1})

#df_clean["alone"] = df_clean["alone"].map({True: 1, False: 0})
#df_clean["embarked"] = df_clean["embarked"].fillna("S").map({"C": 0, "Q": 1, "S": 2})
df_clean.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3  0.0  22.0      1      0   7.2500         2      0
1         1       1  1.0  38.0      1      0  71.2833         0      0
2         1       3  1.0  26.0      0      0   7.9250         2      1
3         1       1  1.0  35.0      1      0  53.1000         2      0
4         0       3  0.0  35.0      0      0   8.0500         2      1

In [44]:
df_clean.isnull().sum()

survived     0
pclass       0
sex         83
age          0
sibsp        0
parch        0
fare         0
embarked     0
alone        0
dtype: int64